//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarm_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public long Id { get; set; }
        public long Sound { get; set; }
        public System.DateTime Time { get; set; }
        public string Description { get; set; }
        public long Schedule { get; set; }
    
        public virtual Sound Sound1 { get; set; }
        public virtual Schedule Schedule1 { get; set; }
    }
}
