//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarm_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASDatabaseEntities : DbContext
    {
        public ASDatabaseEntities()
            : base("name=ASDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alarm> Alarms { get; set; }
        public DbSet<Exception> Exceptions { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Sound> Sounds { get; set; }
        public DbSet<WeeklySchedule> WeeklySchedules { get; set; }
    }
}
