//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace Alarm_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Alarms = new ObservableCollection<Alarm>();
            this.Exceptions = new ObservableCollection<Exception>();
            this.WeeklySchedules = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules1 = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules2 = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules3 = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules4 = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules5 = new ObservableCollection<WeeklySchedule>();
            this.WeeklySchedules6 = new ObservableCollection<WeeklySchedule>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Alarm> Alarms { get; set; }
        public virtual ICollection<Exception> Exceptions { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules1 { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules2 { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules3 { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules4 { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules5 { get; set; }
        public virtual ICollection<WeeklySchedule> WeeklySchedules6 { get; set; }
    }
}
