//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace Alarm_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sound
    {
        public Sound()
        {
            this.Alarms = new ObservableCollection<Alarm>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
    
        public virtual ICollection<Alarm> Alarms { get; set; }
    }
}
