//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarm_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklySchedule
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Monday { get; set; }
        public Nullable<long> Tuesday { get; set; }
        public Nullable<long> Wednesday { get; set; }
        public Nullable<long> Thursday { get; set; }
        public Nullable<long> Friday { get; set; }
        public Nullable<long> Saturday { get; set; }
        public Nullable<long> Sunday { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Schedule Schedule1 { get; set; }
        public virtual Schedule Schedule2 { get; set; }
        public virtual Schedule Schedule3 { get; set; }
        public virtual Schedule Schedule4 { get; set; }
        public virtual Schedule Schedule5 { get; set; }
        public virtual Schedule Schedule6 { get; set; }
    }
}
